### ISSUE TITLE
a2sketch paths disappear for later slides

### ISSUE THREAD

**Issue by openbrian** [arnehilmann/a2sketch#5]
I have 4 slides in my deck.  On sides 3 and 4, the a2sketch paths and styles disappear.

Just a hunch, but I think it's related to duplicate id attributes on the page, spanning multiple diagrams.

**Comment by arnehilmann** [comment]
> If you give me some clue about what's going on here, I can work on fixing it.

PRs are welcome. 
Due to {covid|xmas}-related RL issues, I can't say when I will find some time for this...

**Comment by openbrian** [comment]
I have a working fix written up.  I think you're going to like it ;)  I'll submit a PR soon.

**Comment by arnehilmann** [comment]
Integrated in a2sketch:0.15 (part of markdeck:0.54.1)
